name: "Funny-comments"
on:
  issues: 
    types: [opened]

jobs:
    if: github.event_name == 'issues'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
        id: prComment
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIPHY_TOKEN: ${{ secrets.GIPHY_TOKEN }}
          comment_type: 'gif'
      - name: Print comment URL
        run: echo "Comment URL- ${{ steps.prComment.outputs.comment-url }}"
